packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
  - sharp
catalog:
  "@ai-sdk/openai": 1.3.22
  "@eslint/eslintrc": "3"
  "@hookform/resolvers": 3.9.1
  "@mastra/core": 0.10.3
  "@mastra/libsql": 0.10.1
  "@mastra/loggers": 0.10.1
  "@mastra/memory": 0.10.2
  "@playwright/test": 1.49.1
  "@prisma/client": 6.9.0
  "@radix-ui/react-accordion": 1.2.11
  "@radix-ui/react-alert-dialog": 1.1.4
  "@radix-ui/react-avatar": 1.1.2
  "@radix-ui/react-checkbox": 1.1.3
  "@radix-ui/react-dialog": 1.1.4
  "@radix-ui/react-dropdown-menu": 2.1.4
  "@radix-ui/react-label": 2.1.1
  "@radix-ui/react-popover": 1.1.4
  "@radix-ui/react-radio-group": 1.2.2
  "@radix-ui/react-select": 2.1.4
  "@radix-ui/react-separator": 1.1.1
  "@radix-ui/react-slot": 1.1.1
  "@radix-ui/react-toggle": 1.1.1
  "@radix-ui/react-tooltip": 1.1.6
  "@supabase/ssr": 0.5.2
  "@supabase/supabase-js": 2.47.10
  "@tailwindcss/postcss": 4.1.8
  "@testing-library/dom": 10.4.0
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 16.1.0
  "@testing-library/user-event": 14.5.2
  "@types/node": "20"
  "@types/react": "19"
  "@types/react-dom": 19.0.2
  "@vitejs/plugin-react": 4.3.4
  "@vitest/eslint-plugin": 1.1.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  date-fns: 4.1.0
  eslint: "9"
  eslint-config-next: 15.1.2
  eslint-plugin-playwright: 2.1.0
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-tailwindcss: 3.17.5
  happy-dom: 16.0.1
  lucide-react: 0.469.0
  mastra: 0.10.3
  neostandard: 0.12.0
  next: 15.1.2
  next-themes: 0.4.6
  postcss: "8"
  prettier: 3.4.2
  prisma: 6.9.0
  react: 19.0.0
  react-day-picker: 8.10.1
  react-dom: 19.0.0
  react-hook-form: 7.54.2
  sonner: 2.0.5
  tailwind-merge: 2.5.5
  tailwindcss: 4.1.8
  tailwindcss-animate: 1.0.7
  tsx: 4.20.2
  turbo: 2.5.4
  typescript: "5"
  uuidv7: 1.0.2
  valibot: 1.0.0-beta.9
  vaul: 1.1.2
  vitest: 2.1.8
  zod: 3.24.1
