"use client";

import { createClient } from "@/lib/supabase/browser";
import { RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ログアウト",
  description: "Generated by create next app",
};

export function LogoutPage() {
  const router = useRouter();

  useEffect(() => {
    const client = createClient();
    client.auth.signOut().then(() => {
      router.refresh();
    });
  });

  return (
    <div className="flex h-full max-h-32 flex-col items-center justify-end">
      <div>ログアウト中です</div>
      <RefreshCw className="mt-8 animate-spin" />
    </div>
  );
}
