name: コード品質チェック

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: リントとフォーマットのチェック
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: pnpm のセットアップ
        uses: pnpm/action-setup@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: 依存関係のインストール
        run: pnpm install

      - name: リントチェック
        run: pnpm lint:check

      - name: 型チェック
        run: pnpm type:check

      - name: フォーマットチェック
        run: pnpm format:check
