name: E2Eテスト

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: pnpmのインストール
        uses: pnpm/action-setup@v4

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: 依存関係のインストール
        run: pnpm install --frozen-lockfile

      - name: Supabase CLIのセットアップ
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabaseローカル開発環境の起動
        run: supabase start

      - name: Supabaseの準備完了を待機
        run: |
          until curl -s http://localhost:54321/rest/v1/ > /dev/null; do
            echo "Waiting for Supabase..."
            sleep 5
          done
          echo "Supabase is ready!"

      - name: データベースのセットアップ
        run: pnpm db:reset -- --force
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:54322/postgres?schema=public"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:54322/postgres?schema=public"
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

      - name: Playwrightブラウザのインストール
        run: pnpm --filter web exec playwright install --only-shell

      - name: アプリケーションのビルド
        run: pnpm build
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
          SUPABASE_URL: http://localhost:54321
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
          DATABASE_URL: "postgresql://postgres:postgres@localhost:54322/postgres?schema=public"

      - name: E2Eテストの実行
        run: pnpm test:e2e
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
          SUPABASE_URL: http://localhost:54321
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
          DATABASE_URL: "postgresql://postgres:postgres@localhost:54322/postgres?schema=public"

      - name: テスト結果のアップロード
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 5
